services:

  web:
    build: .
    container_name: notas_alunos
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql_notas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql_data: